# Generated by Django 2.2.9 on 2020-12-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='book',
            new_name='title',
        ),
    ]
