# Generated by Django 2.2.9 on 2020-12-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20201218_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='title',
            new_name='book',
        ),
    ]
