# Generated by Django 2.2.9 on 2020-12-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_shtetl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='owner',
        ),
    ]
